// This file is automatically generated. Do not modify it manually.
export const firebaseConfig = {
  "projectId": "studio-3329979043-5f5b0",
  "appId": "1:10996082844:web:91c87faa4150d69bb7a559",
  "apiKey": "AIzaSyDMSExOswU4gB1ntHAf00O5mf3jQtDB1p8",
  "authDomain": "studio-3329979043-5f5b0.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "10996082844"
};
